output_dir: /itet-stor/trachsele/net_scratch/tl4rec/model_outputs/logs

dataset:
  class: JointDataset
  graphs: [Amazon_Beauty, Amazon_Games]
  root: /itet-stor/trachsele/net_scratch/tl4rec/model_outputs/data

model:
  class: Gru-Ultra
  user_projection:
   hidden_dims: [32]
  item_projection: 
   hidden_dims: [32]
  backbone_model:
    simple_model:
      class: SimpleNBFNet
      input_dim: 40
      hidden_dims: [40, 40,40, 40]
      message_func: distmult
      aggregate_func: sum
      short_cut: yes
      layer_norm: yes
      # CONSTRAINT: entity_model_inputdim = node_embedding_output_dim +  relation_embedding_output_dim
    embedding_user:
      hidden_dims: [32, 32]
    embedding_item:
      hidden_dims: [32, 32]

task:
  name: MultiGraphPretraining
  num_negative: 8
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, ndcg@20]

optimizer:
  class: AdamW
  lr: 5.0e-4

train:
  gpus: [{{ gpus }}]
  batch_size: 4
  num_epoch: 1
  log_interval: 800
  batch_per_epoch: 80000
  fast_test: 500
  wandb: yes
  #logger: wandb