output_dir: /itet-stor/trachsele/net_scratch/tl4rec/model_outputs/logs

dataset:
  class: JointDataset
  graphs: [Amazon_Beauty, Amazon_Games]
  root: /itet-stor/trachsele/net_scratch/tl4rec/model_outputs/data

model:
  class: Gru-Ultra
  node_features: no
  edge_features: yes
  user_projection:
   use_dropout: yes
   dropout_rate: 0.1
   use_layer_norm: yes
   hidden_dims: [32]
  item_projection: 
   use_dropout: yes
   dropout_rate: 0.1
   use_layer_norm: yes
   hidden_dims: [32]
  edge_projection: 
   use_dropout: no
   dropout_rate: 0.1
   use_layer_norm: yes
   hidden_dims: [4]
  backbone_model:
    simple_model:
      class: SimpleNBFNet
      input_dim: 40
      hidden_dims: [40, 40,40, 40]
      message_func: distmult
      aggregate_func: sum
      short_cut: yes
      layer_norm: yes
      project_conv_emb: yes
      # CONSTRAINT: entity_model_inputdim = node_embedding_output_dim +  relation_embedding_output_dim
    embedding_user:
      use_dropout: no
      dropout_rate: 0.1
      use_layer_norm: no
      hidden_dims: [16, 16]
    embedding_item:
      use_dropout: no
      dropout_rate: 0.1
      use_layer_norm: no
      hidden_dims: [16, 16]
    embedding_edge:
      use_dropout: yes
      dropout_rate: 0.05
      use_layer_norm: yes
      hidden_dims: [4, 4, 4]

task:
  name: MultiGraphPretraining
  num_negative: 8
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, ndcg@20]

optimizer:
  class: AdamW
  projection_user_lr: 1.0e-4
  projection_item_lr: 1.0e-4
  projection_edge_lr: 1.0e-4
  backbone_conv_lr: 5.0e-4
  backbone_mlp_user_lr: 5.0e-4
  backbone_mlp_item_lr: 5.0e-4
  backbone_mlp_edge_lr: 5.0e-4

train:
  gpus: [{{ gpus }}]
  batch_size: 8
  num_epoch: 8
  log_interval: 800
  batch_per_epoch: 20000
  fast_test: 500
  wandb: yes
  #logger: wandb
